trigger:
  tags:
    include:
      - 'release/js/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.11.1'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'ci'
  workingDirectory: './sdk/js/packages/client'
  displayName: 'Install Dependencies'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run lint'
  workingDirectory: './sdk/js/packages/client'
  displayName: 'Run Linter'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run check-format'
  workingDirectory: './sdk/js/packages/client'
  displayName: 'Check Format'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
  workingDirectory: './sdk/js/packages/client'
  displayName: 'Build'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'test'
  workingDirectory: './sdk/js/packages/client'
  displayName: 'Test'

- bash: |
    version=${BUILD_SOURCEBRANCHNAME#refs/tags/release/js/}
    echo "##vso[task.setvariable variable=version]$version"

- bash: |    
    npm pkg set version="$(version)"
    mkdir pkg
    cd pkg
    npm pack ..
  workingDirectory: './sdk/js/packages/client'
  displayName: 'Pack'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: './sdk/js/packages/client/pkg/*.tgz'
    artifact: 'npm-package'
  displayName: 'Upload Artifact'

- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'GitHubServiceConnection'
    repositoryName: 'microsoft/ai-chat-protocol'
    action: 'create'
    target: '$(Build.SourceBranch)'
    tagSource: 'manual'
    tag: '$(Build.SourceBranchName)'
    title: 'Typescript Release $(Build.SourceBranchName)'
    assets: './sdk/js/packages/client/pkg/*.tgz'
  displayName: 'Create Release'

- task: AzurePowerShell@5
  displayName: 'Upload files to partner drop folder'
  inputs:
    azureSubscription: 'azuresdkpartnerdrops'
    ScriptType: 'InlineScript'
    azurePowerShellVersion: LatestVersion 
    pwsh: true
    Inline: |
      azcopy copy "./sdk/js/packages/client/pkg/*" "https://azuresdkpartnerdrops.blob.core.windows.net/drops/chat-protocol/npm/$(version)/"
  env: 
    AZCOPY_AUTO_LOGIN_TYPE: 'PSCRED'