trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildId: $(Build.BuildNumber)
  workingDirectory: $(System.DefaultWorkingDirectory)/sdk/js/packages/client

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.11.1'
  displayName: 'Install Node.js'

- checkout: self

- task: Npm@1
  inputs:
    command: 'ci'
    workingDir: $(workingDirectory)
  displayName: 'Install Dependencies'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: $(workingDirectory)
    customCommand: 'lint'
  displayName: 'Run Linter'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: $(workingDirectory)
    customCommand: 'check-format'
  displayName: 'Check Format'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: $(workingDirectory)
    customCommand: 'build'
  displayName: 'Build'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: $(workingDirectory)
    customCommand: 'test'
  displayName: 'Run Tests'

- script: |
    version=$(node -p "require('./package.json').version")
    npm version "${version}-beta.${buildId}" --no-git-tag-version
  displayName: 'Update Version'

- script: |
    npm pack
  displayName: 'npm pack'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '*.tgz'
    artifactName: 'drop'
    publishLocation: 'Container'