services:
  redis:
    image: redis
    ports:
    - 6379:6379

  development:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: vscode
        node_version: 20.11.1
        dotnet_version: 8.0.100
    volumes:
      - ..:/workspace
    ports:
      - 3000:3000
    environment:
      TEST_SERVER_URL: http://test-server:8080
    depends_on:
      - test-server
    command: sleep infinity
