#!/bin/bash

echo "Initializing secrets..."

SECRETS_DIR=$(dirname $(readlink -f $0))

## Fill in the following values with your own keys and endpoints
AZURE_OPENAI_KEY="YOUR_AZURE_OPENAI_KEY"
AZURE_OPENAI_ENDPOINT="YOUR_AZURE_OPENAI_ENDPOINT"
AZURE_OPENAI_DEPLOYMENT="YOUR_AZURE_OPENAI_DEPLOYMENT"
AZURE_MAAS_KEY="YOUR_MAAS_KEY"
AZURE_MAAS_ENDPOINT="YOUR_MAAS_ENDPOINT"
AZURE_MAAP_LLAMA2_KEY="YOUR_LLAMA2_MAAP_KEY"
AZURE_MAAP_LLAMA2_ENDPOINT="YOUR_LLAMA2_MAAP_ENDPOINT"
AZURE_MAAP_LLAMA2_DEPLOYMENT="YOUR_LLAMA2_MAAP_DEPLOYMENT"

echo "$AZURE_OPENAI_KEY" > $SECRETS_DIR/azure_openai_key
echo "$AZURE_OPENAI_ENDPOINT" > $SECRETS_DIR/azure_openai_endpoint
echo "$AZURE_OPENAI_DEPLOYMENT" > $SECRETS_DIR/azure_openai_deployment
echo "$AZURE_MAAS_KEY" > $SECRETS_DIR/maas_key
echo "$AZURE_MAAS_ENDPOINT" > $SECRETS_DIR/maas_endpoint
echo "$AZURE_MAAP_LLAMA2_KEY" > $SECRETS_DIR/llama2_maap_key
echo "$AZURE_MAAP_LLAMA2_ENDPOINT" > $SECRETS_DIR/llama2_maap_endpoint
echo "$AZURE_MAAP_LLAMA2_DEPLOYMENT" > $SECRETS_DIR/llama2_maap_deployment
