name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1'

    - name: Install Dependencies
      run: npm ci
      working-directory: ./sdk/js/packages/client

    - name: Run Linter
      run: npm run lint
      working-directory: ./sdk/js/packages/client

    - name: Check Format
      run: npm run check-format
      working-directory: ./sdk/js/packages/client

    - name: Build
      run: npm run build
      working-directory: ./sdk/js/packages/client

    - name: Test
      run: npm test
      working-directory: ./sdk/js/packages/client

    - name: Update Version
      run: |
        version=$(npm pkg get version | tr -d '"')
        npm pkg set version="${version}-beta.${GITHUB_RUN_NUMBER}"
      working-directory: ./sdk/js/packages/client

    - name: Pack
      run: npm pack
      working-directory: ./sdk/js/packages/client

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: client
        path: ./sdk/js/packages/client/*.tgz